// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDOBb03oCVwiMAO5xXpV415OqKyirGQY',
    appId: '1:651833056316:web:71df0a66e2b72d271e7739',
    messagingSenderId: '651833056316',
    projectId: 'aplikasi-kost-ea478',
    authDomain: 'aplikasi-kost-ea478.firebaseapp.com',
    storageBucket: 'aplikasi-kost-ea478.firebasestorage.app',
    measurementId: 'G-H4WQ9YXYRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9CWK-ZjJfgKFUkMDi-Eg3Ql-pXlGz1w4',
    appId: '1:651833056316:android:52b9921f52a164441e7739',
    messagingSenderId: '651833056316',
    projectId: 'aplikasi-kost-ea478',
    storageBucket: 'aplikasi-kost-ea478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL6iqp9x8U6huAyGnW3QlCeQMUNNCKC7c',
    appId: '1:651833056316:ios:2435a6e7e8136a7f1e7739',
    messagingSenderId: '651833056316',
    projectId: 'aplikasi-kost-ea478',
    storageBucket: 'aplikasi-kost-ea478.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiKost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL6iqp9x8U6huAyGnW3QlCeQMUNNCKC7c',
    appId: '1:651833056316:ios:2435a6e7e8136a7f1e7739',
    messagingSenderId: '651833056316',
    projectId: 'aplikasi-kost-ea478',
    storageBucket: 'aplikasi-kost-ea478.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiKost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGDOBb03oCVwiMAO5xXpV415OqKyirGQY',
    appId: '1:651833056316:web:0297289cd8601d691e7739',
    messagingSenderId: '651833056316',
    projectId: 'aplikasi-kost-ea478',
    authDomain: 'aplikasi-kost-ea478.firebaseapp.com',
    storageBucket: 'aplikasi-kost-ea478.firebasestorage.app',
    measurementId: 'G-61BSMEL16K',
  );
}
